---
title: "Compare Sites/Samples - PCA"
author: "Ava Hoffman"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)  # CRAN v2.0.0
library(caret)      # CRAN v7.0-1
library(factoextra) # CRAN v1.0.7
```

## Load Data

```{r}
# Choose one: data_source <- c("local", "github", "google")
data_source <- "google"
```


```{r}
if (data_source == "local") {
  # Look in pwd for specific snapshots
  sites_full <- read_csv("data/snapshots/BioDIGS_sites_20250929.csv")
  soil_full <- read_csv("data/snapshots/BioDIGS_soil_20250929.csv")
} else if (data_source == "google") {
  # All from Google (need access)
  googlesheets4::gs4_auth(email = T)
  sites_full <- googlesheets4::read_sheet(
    "https://docs.google.com/spreadsheets/d/1Mbuym6GgG2B3VFCbjhYy4vaPCx1_tIOBlBOlT1iIHZE/edit?gid=476949426#gid=476949426",
    sheet = "SITE DATA"
  )
  soil_full <- googlesheets4::read_sheet(
    "https://docs.google.com/spreadsheets/d/1Mbuym6GgG2B3VFCbjhYy4vaPCx1_tIOBlBOlT1iIHZE/edit?gid=476949426#gid=476949426",
    sheet = "SOIL SAMPLES",
    col_types = "c"
  )
} else {
  # Public snapshot on github if not downloaded
  sites_full <- read_csv(
    "https://github.com/FredHutch/GDSCNsoilsites/raw/refs/heads/main/data/snapshots/BioDIGS_sites_20250929.csv"
  )
  soil_full <- read_csv(
    "https://github.com/FredHutch/GDSCNsoilsites/raw/refs/heads/main/data/snapshots/BioDIGS_soil_20250929.csv"
  )
}
```

## Data cleanup

Drop some extra metadata columns:

```{r}
sites <- sites_full %>%
  select(c(site_id, origin, gps, mgmt_type, pct_imp_2024)) %>%
  mutate(origin = case_when(
    origin %in% c("Derwood, MD", "Boyds, MD", "Germantown, MD", "Bethesda, MD") ~ "Montgomery Co., MD",
    TRUE ~ origin
  ))
soil <- soil_full %>% select(
  c(
    collection_date,
    site_id,
    sample_id,
    ends_with("EPA3051"),
    water_pH,
    OM_by_LOI_pct,
    ends_with("Mehlich3"),
    Est_CEC,
    Base_Sat_pct,
    P_Sat_ratio
  )
)
```

Add `NA` and clean some values and classes

```{r}
soil <- 
  soil %>%
  mutate(across(everything(), ~ na_if(., "Not yet tested"))) %>%
  mutate(As_EPA3051 = case_when(As_EPA3051 %in% c("< 3.0", "<3.0") ~ "0", TRUE ~ As_EPA3051)) %>% 
  mutate(Cd_EPA3051 = case_when(Cd_EPA3051 %in% c("< 0.2", "<0.2") ~ "0", TRUE ~ Cd_EPA3051)) %>% 
  mutate(Cu_EPA3051 = case_when(Cu_EPA3051 %in% c("< 2.0", "<2.0") ~ "0", TRUE ~ Cu_EPA3051)) %>% 
  drop_na() %>% 
  mutate(across(4:27, as.numeric))

sites <-
  sites %>%
  tidyr::separate(gps, into = c("lat", "lon"), sep = ", ") %>%
  mutate(
    mgmt_type = case_when(
      mgmt_type %in% c(
        "Botanical Garden",
        "Mowed to control kudzu, but other than that unmanaged area"
      ) ~ "Managed: mowed/tended lawns, yard, or park",
      mgmt_type == "not yet provided" ~ NA,
      TRUE ~ mgmt_type
    )
  ) %>% # Group a few single mgmt types
  mutate(mgmt_type = as.numeric(as.factor(mgmt_type))) %>% # Make factor and numeric
  drop_na() %>%
  mutate(across(c(3:6), as.numeric)) %>%
  mutate(mgmt_type = as.factor(mgmt_type))

mgmt_dummy <- dummyVars(" ~ .", data = sites[, "mgmt_type"])
mgmt_onehot <- data.frame(predict(mgmt_dummy, newdata = sites[, "mgmt_type"]))

sites <-
  sites %>% select(!mgmt_type) %>% bind_cols(mgmt_onehot)
```

## Sample level/scale

What is the PCA pattern at the sample level?

```{r}
# Includes soil characteristics, gps coords, mgmt type, environment etc.
sample_level <- soil %>% left_join(sites, by = join_by(site_id))

# Drop non-numeric columns
sample_level_pca <-
  sample_level %>%
  mutate(label = stringr::str_remove(sample_id, "Soil_")) %>%
  column_to_rownames("label") %>%
  select(!c(origin, collection_date, site_id, sample_id))


# Run PCA
pca_out <- prcomp(sample_level_pca, scale = TRUE)
summary(pca_out)

# Scree Plot: % Variance explained by different PCs
eig_val <- get_eigenvalue(pca_out)
p1 <- fviz_eig(pca_out, col.var = "blue")

# Correlation of variables in each PC
pca_var <- get_pca_var(pca_out)
p2 <- ggcorrplot::ggcorrplot(pca_var$cos2[, 1:2]) + theme(legend.position = "none")

# PCA labeled by sample
p3 <- fviz_pca_ind(pca_out, repel = F)

# PCA colored by origin
p4 <- fviz_pca_ind(
  pca_out,
  label = "none",
  habillage = sample_level$origin,
  mean.point = F,
  palette = viridis::magma(n = length(unique(
    sample_level$origin
  )), end = 0.9)
) + ggtitle("PCA: Sample level soil and site characteristics") + theme(legend.title = element_blank())

# Save combined plot
cowplot::plot_grid(p4, p2, ncol = 1, rel_heights = c(8, 2))
ggsave(
  "figures/PCA_by_sample.png",
  height = 10,
  width = 8,
  dpi = "print"
)
```

## Site level, with soil

What is the PCA pattern at the site level?

```{r}
# Includes soil characteristics, gps coords, mgmt type, environment etc.
site_level <- soil %>% select(!c(collection_date, sample_id)) %>% group_by(site_id) %>% 
  summarize(across(everything(), mean)) %>% 
  left_join(sites, by = join_by(site_id))

# Drop non-numeric columns
site_level_pca <-
  site_level %>%
  column_to_rownames("site_id") %>%
  select(!c(origin))


# Run PCA
pca_out <- prcomp(site_level_pca, scale = TRUE)
summary(pca_out)

# Scree Plot: % Variance explained by different PCs
eig_val <- get_eigenvalue(pca_out)
p1 <- fviz_eig(pca_out, col.var = "blue")

# Correlation of variables in each PC
pca_var <- get_pca_var(pca_out)
p2 <- ggcorrplot::ggcorrplot(pca_var$cos2[, 1:2]) + theme(legend.position = "none")

# PCA labeled by site
p3 <- fviz_pca_ind(pca_out, repel = F)

# PCA colored by origin
p4 <- fviz_pca_ind(
  pca_out,
  label = "none",
  habillage = site_level$origin,
  mean.point = F,
  palette = viridis::magma(n = length(unique(
    site_level$origin
  )), end = 0.9)
) + ggtitle("PCA: Site level soil and site characteristics") + theme(legend.title = element_blank())

# Save combined plot
cowplot::plot_grid(p4, p2, ncol = 1, rel_heights = c(8, 2))
ggsave(
  "figures/PCA_by_site.png",
  height = 10,
  width = 8,
  dpi = "print"
)
```

## Site level, without soil

What is the PCA pattern at the site level, using mainly public data, with no soil characteristic data?

```{r}
# Sites only.. drop non-numeric columns
site_level_pca <-
  sites %>%
  rownames_to_column("drop") %>% 
  select(!drop) %>% 
  column_to_rownames("site_id") %>%
  select(!c(origin))


# Run PCA
pca_out <- prcomp(site_level_pca, scale = TRUE)
summary(pca_out)

# Scree Plot: % Variance explained by different PCs
eig_val <- get_eigenvalue(pca_out)
p1 <- fviz_eig(pca_out, col.var = "blue")

# Correlation of variables in each PC
pca_var <- get_pca_var(pca_out)
p2 <- ggcorrplot::ggcorrplot(pca_var$cos2[, 1:2]) + theme(legend.position = "none")

# PCA labeled by site
p3 <- fviz_pca_ind(pca_out, repel = F)

# PCA colored by origin
p4 <- fviz_pca_ind(
  pca_out,
  label = "none",
  habillage = sites$origin,
  mean.point = F,
  palette = viridis::magma(n = length(unique(
    sites$origin
  )), end = 0.9)
) + ggtitle("PCA: Site level characteristics only (no soil measures)") + theme(legend.title = element_blank())

# Save combined plot
cowplot::plot_grid(p4, p2, ncol = 1, rel_heights = c(8, 2))
ggsave(
  "figures/PCA_by_site_no_soil.png",
  height = 10,
  width = 8,
  dpi = "print"
)
```
